[package]
edition = "2018"
name = "jujutsu-discord"
version = "0.0.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
colored = "2.0.0"
futures = "0.3.25"
futures-util = "0.3.25"
mio = { version = "0.8.5", features = ["os-poll", "net"] }
ms = "0.1.1"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.10.2", default-features = false, features = ["napi4", "async"] }
napi-derive = "2.9.3"
rand = "0.8.5"
serde = "1.0.149"
serde_json = "1.0.89"
tungstenite = { version = "0.18.0", features = ["native-tls"]}
async-tungstenite = {  version = "*", features = ["tokio-runtime"] }
url = "2.2.2"
bitflags = "1.3.2"
tokio = { verison = "1.23.0", features = ["full"] }
titlecase = "2.2.1"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
