[package]
edition = "2021"
name = "jujutsu-discord"
version = "0.0.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
colored = "2.0.0"
futures = "0.3.25"
futures-util = "0.3.25"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.10.2", default-features = false, features = ["napi4", "async"] }
napi-derive = "2.9.3"
serde = "1.0.149"
serde_json = "1.0.89"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
