'area: app':
  - 'App directory (appDir: true)'
'area: create-berserk-app':
  - 'CLI (create-berserk-app)'
'area: package manager':
  - 'Package manager (npm, pnpm, Yarn)'
'area: SWC minify':
  - 'SWC minifier (swcMinify: true)'
'area: SWC transforms':
  - 'SWC transpilation'
'area: TypeScript':
  - 'TypeScript'
