[package]
edition = "2018"
name = "discord"
version = "0.0.0"
publish = false

[dependencies]
chrono = "0.4"
easy-error = "1.0.0"
either = "1"
fxhash = "0.2.1"
once_cell = "1.13.0"
pathdiff = "0.2.0"
regex = "1.5"
serde = "1"
serde_json = "1"
tokio = { version ="1.23.0", features = ["full", "sync", "tracing"] }
tracing = { version = "0.1.37", features = ["release_max_level_info"] }
tungstenite = { version = "0.18.0", features = ["native-tls", "rustls", "__rustls-tls"] }
url = "2.3.1"

[dev-dependencies]
walkdir = "2.3.2"
