[package]
edition = "2018"
name = "wasm"
publish = false
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.66"
console_error_panic_hook = "0.1.6"
discord = {version = "0.0.0", path = "../core"}
once_cell = "1.13.0"
parking_lot_core = "=0.8.0"
path-clean = "0.1"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
tracing = { version = "0.1.37", features = ["release_max_level_off","max_level_off"] }
wasm-bindgen = {version = "0.2", features = ["enable-interning"]}
wasm-bindgen-futures = "0.4.8"
getrandom = { version = "0.2.5", optional = true, default-features = false }
js-sys = "0.3.59"
serde-wasm-bindgen = "0.4.3"

# Workaround a bug
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

# Workaround a bug
[package.metadata.wasm-pack.profile.dev]
wasm-opt = false